import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/auth/[...nextauth]/route';
import Link from 'next/link';
import { redirect } from 'next/navigation';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const isAdmin = session?.user?.role === 'ADMIN';
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-gray-800 text-white p-4 flex justify-between">
          <Link href="/" className="font-bold">ElevateX</Link>
          <div className="space-x-4">
            <Link href="/menu">Menu</Link>
            <Link href="/reservation">Reservation</Link>
            <Link href="/order">Order</Link>
            {isAdmin && <Link href="/admin/dashboard">Admin</Link>}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
